#! /bin/sh
### BEGIN INIT INFO
# Provides:          vpnclient
# Should-Start:      console-screen dbus network-manager
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SoftEther VPN Client
# Description:       SoftEther VPN Client
### END INIT INFO
#
# Author:       Luke Luo
#
set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/vpnclient/vpnclient

test -x $DAEMON || exit 0

if [ -r /etc/default/locale ]; then
  . /etc/default/locale
  export LANG LANGUAGE
fi

. /lib/lsb/init-functions



case "$1" in
  start)
	$DAEMON start
  ;;
  stop)
	$DAEMON stop
  ;;
  reload)
	$DAEMON stop
	$DAEMON start
  ;;
  status)
        
  ;;
  restart|force-reload)
	$DAEMON stop
	$DAEMON start
  ;;
  *)
        echo "Usage:vpnclient {start|stop|restart|status}"
        exit 1
  ;;
esac

exit 0
